export const MessagesEn = {
	locale: "en",
	messages: {
		"empty": " ",
		"Home": "Home",
		"Logout": "Logout",
		"Login": "Login",
		"Log in": "Log in",
		"reset.password": "Password forgotten?",
		"Registration": "Registration",
		"Profile": "Profile",
		"Password": "Password",
		"Save": "Save",
		"Cancel": "Cancel",
		"Or": "Or ",
		"Tasks": "Tasks",
		"Description": "description",
		"Deadline": "Deadline",
		"archive": "Archive",
		"in.archive": "Archive",
		"add.task": "Add task",
		"add.status": "Add status",
		"add.project": "Add project",

		"username": "Username",
		"username.email": "Username or email",
		"register.now": "register now!",
		"remember.me": "Remember me",
		"change.password": "Change password",
		"task.name": "Task name",
		"project.name": "Project name",

		"message.username_email": "Please input your username or email!",
		"message.username": "Please input your username!",
		"message.email": "Please input your email!",
		"message.password": "Please input your Password!",
		"message.captcha": "Please input the captcha!",
		"message.task.name": "Task name",
		"message.task.description": "Task description",
		"message.project.name": "Project name",
		"message.status.name": "Status title",

	},
};

export const MessagesRu = {
	locale: "ru",
	messages: {
		"empty": " ",
		"Home": "Главная",
		"Logout": "Выйти",
		"Login": "Войти",
		"Log in": "Войти",
		"reset.password": "Забыли пароль?",
		"Registration": "Регистрация",
		"Profile": "Профиль",
		"Password": "Пароль",
		"Save": "Сохранить",
		"Cancel": "Отменить",
		"Or": "Или ",
		"Tasks": "Задачи",
		"Description": "Описание",
		"Deadline": "Дата выполнения",
		"archive": "Архив",
		"in.archive": "Архивировать",
		"add.task": "Добавить задачу",
		"add.status": "Добавить статус",
		"add.project": "Добавить проект",

		"username": "Имя пользователя",
		"username.email": "Имя пользователя или email",
		"register.now": "зарегистрируйтесь сейчас!",
		"remember.me": "Запомнить меня",
		"change.password": "Изменить пароль",
		"task.name": "Название задачи",
		"project.name": "Название проекта",

		"message.username_email": "Пожалуйста, введите ваше Имя пользователя или email",
		"message.username": "Пожалуйста, введите ваше Имя пользователя!",
		"message.email": "Пожалуйста, введите ваш email!",
		"message.password": "Пожалуйста, введите ваш пароль!",
		"message.captcha": "Пожалуйста, введите капчу!",
		"message.task.name": "Название задачи",
		"message.task.description": "Описание задачи",
		"message.project.name": "Название проекта",
		"message.status.name": "Название статуса",

	},
};
